export const actionArray = {
  LOGIN: "LOGIN",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_SERVICIO",
  GET_SERVICIOS: "GET_SERVICIOS",
  UPDATE_SERVICIO: "UPDATE_SERVICIO",
  DELETE_SERVICIO: "DELETE_SERVICIO",
  CREATE_SERVICIO: "CREATE_SERVICIO",
  GET_TRABAJOS: "GET_TRABAJOS",
  UPDATE_TRABAJO: "UPDATE_TRABAJO",
  DELETE_TRABAJO: "DELETE_TRABAJO",
  CREATE_TRABAJO: "CREATE_TRABAJO"
};
